SmartQrProject/SmartQr-Back

- smart-qr-app/package-lock.json
- smart-qr-app/package.json
- smart-qr-app/src/app.module.ts
- smart-qr-app/src/modules/chatbot/chatbot.gateway.ts
- smart-qr-app/src/modules/chatbot/chatbot.module.ts
- smart-qr-app/src/modules/chatbot/chatbot.service.ts
- smart-qr-app/src/modules/chatbot/dto/message.dto.ts
- smart-qr-app/src/modules/chatbot/types/chatbot-events.ts
- smart-qr-app/src/modules/chatbot/user-session/user-session.service.ts
- smart-qr-app/src/modules/users/users.controller.ts
- smart-qr-app/src/modules/users/users.module.ts
- smart-qr-app/src/modules/users/users.repository.ts
- smart-qr-app/src/modules/users/users.service.ts
Chat bot socket and user endpoint modification
> Chat bot socket /users

- smart-qr-app/src/common/guards/jwt-auth0.guard.ts
- smart-qr-app/src/common/guards/jwtAuth0Guard.ts
- smart-qr-app/src/common/services/jwt.strategy4Auth0.ts
- smart-qr-app/src/modules/authCustomers/authCustomers.controller.ts
- smart-qr-app/src/modules/authCustomers/authCustomers.module.ts
> Ver 2025-05-14 Ver00

- smart-qr-app/src/modules/restaurants/restaurants.service.ts
Refactor RestaurantsService to use BcryptService for password hashing
> Refactor RestaurantsService to use BcryptService for password hashing

- smart-qr-app/src/modules/categories/categories.controller.ts
- smart-qr-app/src/modules/categories/categories.module.ts
- smart-qr-app/src/modules/categories/categories.repository.ts
- smart-qr-app/src/modules/categories/categories.service.ts
- smart-qr-app/src/modules/categories/dto/create-category.dto.ts
- smart-qr-app/src/modules/categories/dto/update-category.dto.ts
> Categories

- smart-qr-app/src/modules/categories/categories.controller.ts
- smart-qr-app/src/modules/products/dto/create-product.dto.ts
- smart-qr-app/src/modules/products/dto/update-product.dto.ts
- smart-qr-app/src/modules/products/products.controller.ts
- smart-qr-app/src/modules/products/products.module.ts
- smart-qr-app/src/modules/products/products.repository.ts
- smart-qr-app/src/modules/products/products.service.ts
- smart-qr-app/src/modules/restaurants/restaurants.service.ts
- smart-qr-app/src/shared/entities/product.entity.ts
Implementacion de Products + Pequeño fix en categorias con el slug.
> Products + Categories Fix

- smart-qr-app/package-lock.json
- smart-qr-app/package.json
- smart-qr-app/src/common/common.module.ts
- smart-qr-app/src/common/services/mail.service.ts
- smart-qr-app/src/config/env.loader.ts
- smart-qr-app/src/modules/customers/customers.module.ts
- smart-qr-app/src/modules/customers/customers.service.ts
> 2do sprint nodemailer

- smart-qr-app/src/common/emailTemplates/generalEmailTemplate.html
- smart-qr-app/src/common/services/mail.service.ts
- smart-qr-app/src/modules/customers/customers.repository.ts
- smart-qr-app/src/modules/customers/customers.service.ts
> 3er Sprint nodemailer

- smart-qr-app/src/modules/categories/categories.controller.ts
- smart-qr-app/src/modules/categories/categories.module.ts
- smart-qr-app/src/modules/categories/categories.repository.ts
- smart-qr-app/src/modules/categories/dto/create-category.dto.ts
- smart-qr-app/src/modules/categories/dto/update-category.dto.ts
- smart-qr-app/src/modules/products/dto/create-product.dto.ts
- smart-qr-app/src/modules/products/products.controller.ts
- smart-qr-app/src/modules/products/products.repository.ts
- smart-qr-app/src/modules/restaurants/dto/create-restaurants.dto.ts
- smart-qr-app/src/modules/restaurants/restaurants.controller.ts
- smart-qr-app/src/modules/users/dto/signIn-user.dto.ts
- smart-qr-app/src/modules/users/users.controller.ts
Faltaria: Ver borrado logico tanto de products como de categories.
Filtrar products cuando tomamos las categorias(que esten active)
Estandarizar mensajes en ingles.
checkear sequence(probablemente borrar)
> Sw example

- smart-qr-app/src/modules/users/users.service.ts
Add Restaurant entity to the JWT token payload at user login
> Add Restaurant entity to the JWT token payload at user login

- smart-qr-app/src/modules/orders/orders.controller.ts
- smart-qr-app/src/modules/restaurant-tables/restaurant-tables.controller.ts
…ncluir el parámetro 'slug' en el método findAll
> Actualizar los controladores de órdenes y mesas de restaurante para incluir el parámetro 'slug' en el método findAll

- smart-qr-app/src/modules/restaurant-tables/restaurant-tables.module.ts
- smart-qr-app/src/modules/restaurant-tables/restaurant-tables.repository.ts
> 1er Sprint Rest Tables

- smart-qr-app/src/modules/restaurant-tables/dto/create-restaurant-table.dto.ts
- smart-qr-app/src/modules/restaurant-tables/restaurant-tables.controller.ts
- smart-qr-app/src/modules/restaurant-tables/restaurant-tables.module.ts
- smart-qr-app/src/shared/entities/restaurant-table.entity.ts
> 2do Sprint Rest Tables

- smart-qr-app/package-lock.json
- smart-qr-app/package.json
- smart-qr-app/src/modules/restaurant-tables/dto/create-restaurant-table.dto.ts
- smart-qr-app/src/modules/restaurant-tables/dto/update-restaurant-table.dto.ts
- smart-qr-app/src/modules/restaurant-tables/restaurant-tables.controller.ts
- smart-qr-app/src/modules/restaurant-tables/restaurant-tables.repository.ts
- smart-qr-app/src/modules/restaurant-tables/restaurant-tables.service.ts
- smart-qr-app/src/pipes/validateImage.pipe.ts
> Rest tables

- smart-qr-app/src/modules/users/swagger/user-doc.decorator.ts
- smart-qr-app/src/modules/users/users.controller.ts
> Agregado EP /users/staff2

- smart-qr-app/src/modules/restaurants/dto/create-restaurants.dto.ts
- smart-qr-app/src/modules/restaurants/dto/patch-restaurants.dto.ts
- smart-qr-app/src/modules/restaurants/restaurants.controller.ts
- smart-qr-app/src/modules/restaurants/restaurants.module.ts
- smart-qr-app/src/modules/restaurants/restaurants.service.ts
- smart-qr-app/src/modules/restaurants/swagger/restaurants-doc.decorator.ts
- smart-qr-app/src/modules/users/users.repository.ts
Patch para Restaurant, nodemailer para alta y modificacion actualuuzacion de Dto.....
> TriggersNodeMailerAdded 1er

- smart-qr-app/src/modules/products/products.module.ts
- smart-qr-app/src/modules/products/products.repository.ts
- smart-qr-app/src/modules/products/products.service.ts
Agregado de nodemail a Productos
> TriggersNodeMailerAdded 2do

- smart-qr-app/src/modules/categories/categories.module.ts
- smart-qr-app/src/modules/categories/categories.service.ts
Agregado de nodemailer a Categorias
> TriggersNodeMailerAdded 3ro

- smart-qr-app/src/modules/users/users.repository.ts
- smart-qr-app/src/modules/users/users.service.ts
> TriggersNodeMailerAdded 5to

- smart-qr-app/src/modules/orders/orders.module.ts
- smart-qr-app/src/modules/orders/orders.service.ts
> nodemail en Order Creation

- smart-qr-app/src/modules/users/users.controller.ts
agregado de rol staff en el controller de users patch
> Cambio segurida en EP users

- smart-qr-app/src/modules/categories/categories.controller.ts
- smart-qr-app/src/modules/categories/categories.service.ts
- smart-qr-app/src/modules/categories/swagger/categories.decorator.ts
- smart-qr-app/src/modules/users/users.service.ts
cambios en la seguridad de EP de Categories
> Cambio seguridad en EP Categorias

- smart-qr-app/src/modules/restaurants/restaurants.controller.ts
- smart-qr-app/src/modules/restaurants/restaurants.service.ts
- smart-qr-app/src/modules/restaurants/swagger/restaurants-doc.decorator.ts
> Triggers node mails

- smart-qr-app/src/common/services/mail.service.ts
- smart-qr-app/src/modules/cron/cron.module.ts
- smart-qr-app/src/modules/cron/reports-cron.service.ts
- smart-qr-app/src/modules/restaurants/restaurants.service.ts
Modificaciones al restaruant service para borar usuarios cuando se borra el restaurant
> Reportes xmail

- smart-qr-app/src/modules/stripe/stripe.service.ts
- smart-qr-app/src/modules/subscription/subscription.controller.ts
- smart-qr-app/src/modules/subscription/subscription.module.ts
- smart-qr-app/src/modules/subscription/subscription.service.ts
- smart-qr-app/src/modules/subscription/swagger/subscription.decorator.ts
- smart-qr-app/src/shared/entities/subscription.entity.ts
- Added cancelSubscription method in SubscriptionService to handle subscription cancellations via Stripe.
- Introduced SubscriptionController with a PATCH endpoint for cancelling subscriptions.
- Enhanced StripeService to manage subscription updates and cancellations.
- Updated Subscription entity to include cancelAtPeriodEnd flag.
- Created CancelSubscriptionDoc for Swagger documentation.
> Implement cancellation of subscriptions and update metadata handling

- smart-qr-app/src/modules/orders/orders.service.ts
> mail de orders mejorado

- smart-qr-app/src/modules/cloudinary/cloudinary.controller.ts
> cloudinary

- smart-qr-app/src/modules/orders/orders.service.ts
correcion busqueda de mesas por codigo y codi de rest
> correcion tables

- smart-qr-app/src/modules/categories/categories.service.ts
sacar sequence number en el email de tables
> Order table correction

- smart-qr-app/src/modules/restaurant-tables/restaurant-tables.service.ts
- smart-qr-app/src/modules/restaurant-tables/swagger/restaurant-tables-doc.decorator.ts
- smart-qr-app/src/modules/reward-code/swagger/reward-code-doc.decorator.ts
decoradores swagger restaurant tables
> Gea documentacion

- smart-qr-app/src/modules/categories/swagger/categories.decorator.ts
DECORADORES SWAGGER CATEGORIES
> swaggerCATEGORIES

- smart-qr-app/src/modules/users/swagger/user-doc.decorator.ts
> swaggerUsers

- smart-qr-app/src/modules/categories/swagger/categories.decorator.ts
- smart-qr-app/src/modules/customers/swagger/customers-doc.decorator.ts
- smart-qr-app/src/modules/orders/swagger/orders.decorator.ts
- smart-qr-app/src/modules/restaurant-tables/swagger/restaurant-tables-doc.decorator.ts
- smart-qr-app/src/modules/reward-code/swagger/reward-code-doc.decorator.ts
- smart-qr-app/src/modules/users/swagger/user-doc.decorator.ts
> swaggerxxxxx
